name: "build & release"
on:
    push:
        tags: [ 'v*.*.*' ]
        branches:
            - main
            - developement
jobs:
    build:
        name: "build"
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses : actions/checkout@v3

            - name: setup java 
              uses : actions/setup-java@v3
              with: 
                distribution: 'oracle'
                java-version: '17'
                cache: 'gradle'

            - name: setup flutter
              uses: subosito/flutter-action@v2
              with: 
                flutter-version: "3.16.5"
                channel: 'stable'
                cache: true

            - name: Install dependency
              run : flutter pub get
            
            - name : test flutter app
              run: flutter test
            
            - name : build apk file
              run : flutter build apk --release

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                name : Releases
                path: |
                 build/app/outputs/flutter-apk/app-release.apk

            - name: create release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "build/app/outputs/flutter-apk/app-release.apk"
                tag: ${{github.ref_name}} 
                token: ${{secrets.TOKEN}}

            

    